package com.android.git.ui.screens

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import androidx.activity.compose.BackHandler
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.expandVertically
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.shrinkVertically
import androidx.compose.animation.slideInVertically
import androidx.compose.animation.slideOutVertically
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.focus.FocusDirection
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalFocusManager
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.android.git.R
import com.android.git.data.GitAuthConfig
import com.android.git.data.GitAuthManager
import com.android.git.data.GitAuthMode
import com.android.git.data.GitRemoteUrl
import com.android.git.data.PreferencesManager
import com.android.git.ui.components.ExpandableSshTextField
import com.android.git.ui.components.SnackbarType
import com.android.git.ui.viewmodel.MainViewModel
import java.io.File

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CloneScreen(
    viewModel: MainViewModel,
    onBack: () -> Unit,
    onCloneSuccess: (File) -> Unit
) {
    val context = LocalContext.current
    val prefsManager = remember { PreferencesManager(context) }
    val authManager = remember { GitAuthManager(context.filesDir) }
    val focusManager = LocalFocusManager.current

    val activeToken = remember { prefsManager.getToken() }
    val lastUsedToken = remember { prefsManager.getLastValidToken() }
    val initialAuthMode = remember { prefsManager.getAuthMode() }

    var repoUrl by remember { mutableStateOf("") }
    var folderName by remember { mutableStateOf("") }
    var autoGeneratedName by remember { mutableStateOf("") }
    var token by remember { mutableStateOf(activeToken) }
    var saveToken by remember { mutableStateOf(activeToken.isNotEmpty()) }
    var authMode by remember { mutableStateOf(initialAuthMode) }
    var sshPrivateKey by remember { mutableStateOf(prefsManager.getSshPrivateKey()) }
    var sshPublicKey by remember { mutableStateOf(prefsManager.getSshPublicKey()) }
    var sshPassphrase by remember { mutableStateOf(prefsManager.getSshPassphrase()) }
    var sshGenerationError by remember { mutableStateOf("") }
    var sshGenerationInfo by remember { mutableStateOf("") }

    // State to track if the token is visible or hidden
    var tokenVisible by remember { mutableStateOf(false) }

    val isLoading = viewModel.isLoading
    val statusMessage = viewModel.statusMessage
    val statusType = viewModel.statusType
    
    val cloneProgress = viewModel.cloneProgress
    val cloneTaskName = viewModel.cloneTaskName
    val cloneTaskDetails = viewModel.cloneTaskDetails

    val textFieldShape = RoundedCornerShape(16.dp)

    val parsedRemoteUrl = remember(repoUrl) { GitRemoteUrl.parse(repoUrl) }
    val sshRemoteUrl = remember(repoUrl) { GitRemoteUrl.toSshUrl(repoUrl) }

    LaunchedEffect(repoUrl) {
        val cleanUrl = repoUrl.trim().removeSuffix("/")
        if (cleanUrl.contains("/")) {
            val name = cleanUrl.substringAfterLast("/").removeSuffix(".git")
            if (name.isNotBlank() && (folderName.isEmpty() || folderName == autoGeneratedName)) {
                folderName = name
                autoGeneratedName = name
            }
        }
    }

    // Only intercept and block back press if loading is true
    BackHandler(enabled = isLoading) { }

    // Clear state smoothly when leaving the screen naturally
    DisposableEffect(Unit) {
        onDispose { viewModel.clearStatus() }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.clone_title), fontWeight = FontWeight.SemiBold) },
                navigationIcon = {
                    IconButton(onClick = onBack, enabled = !isLoading) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = stringResource(R.string.action_back)
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surface,
                    titleContentColor = MaterialTheme.colorScheme.onSurface
                )
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(horizontal = 16.dp)
                .verticalScroll(rememberScrollState()),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Spacer(modifier = Modifier.height(16.dp))

            ElevatedCard(
                modifier = Modifier.fillMaxWidth(),
                shape = MaterialTheme.shapes.large,
                colors = CardDefaults.elevatedCardColors(
                    containerColor = MaterialTheme.colorScheme.surfaceContainerLow
                ),
                elevation = CardDefaults.elevatedCardElevation(defaultElevation = 2.dp)
            ) {
                Column(modifier = Modifier.padding(20.dp)) {

                    Text(
                        text = stringResource(R.string.repo_settings_section_remote),
                        style = MaterialTheme.typography.labelLarge,
                        color = MaterialTheme.colorScheme.primary,
                        modifier = Modifier.padding(bottom = 12.dp)
                    )

                    OutlinedTextField(
                        value = repoUrl,
                        onValueChange = { repoUrl = it },
                        label = { Text(stringResource(R.string.clone_url_label)) },
                        placeholder = { Text(stringResource(R.string.clone_url_placeholder)) },
                        leadingIcon = { Icon(Icons.Default.Link, contentDescription = null) },
                        trailingIcon = {
                            Row {
                                IconButton(
                                    onClick = {
                                        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as? ClipboardManager
                                        if (repoUrl.isBlank()) {
                                            clipboard?.primaryClip?.getItemAt(0)?.coerceToText(context)?.toString()?.let {
                                                repoUrl = it
                                            }
                                        } else {
                                            clipboard?.setPrimaryClip(ClipData.newPlainText("Git repository URL", repoUrl))
                                        }
                                    },
                                    enabled = !isLoading
                                ) {
                                    Icon(
                                        imageVector = if (repoUrl.isBlank()) Icons.Default.ContentPaste else Icons.Default.ContentCopy,
                                        contentDescription = stringResource(
                                            if (repoUrl.isBlank()) R.string.clone_url_paste else R.string.clone_url_copy
                                        )
                                    )
                                }
                                if (sshRemoteUrl != null && !GitRemoteUrl.isSsh(repoUrl)) {
                                    IconButton(
                                        onClick = { repoUrl = sshRemoteUrl },
                                        enabled = !isLoading
                                    ) {
                                        Icon(
                                            Icons.Default.AutoFixHigh,
                                            contentDescription = stringResource(R.string.clone_url_use_ssh)
                                        )
                                    }
                                }
                            }
                        },
                        isError = repoUrl.isNotBlank() && parsedRemoteUrl == null,
                        supportingText = {
                            when {
                                repoUrl.isNotBlank() && parsedRemoteUrl == null ->
                                    Text(stringResource(R.string.clone_url_invalid))
                                GitRemoteUrl.isSsh(repoUrl) ->
                                    Text(stringResource(R.string.clone_url_ssh_hint))
                            }
                        },
                        modifier = Modifier.fillMaxWidth(),
                        shape = textFieldShape,
                        keyboardOptions = KeyboardOptions(
                            keyboardType = KeyboardType.Uri,
                            imeAction = ImeAction.Next
                        ),
                        keyboardActions = KeyboardActions(
                            onNext = { focusManager.moveFocus(FocusDirection.Down) }
                        ),
                        enabled = !isLoading,
                        maxLines = Int.MAX_VALUE
                    )

                    Spacer(Modifier.height(16.dp))

                    OutlinedTextField(
                        value = folderName,
                        onValueChange = { folderName = it },
                        label = { Text(stringResource(R.string.clone_folder_label)) },
                        placeholder = { Text(stringResource(R.string.clone_folder_hint)) },
                        leadingIcon = { Icon(Icons.Default.Folder, contentDescription = null) },
                        modifier = Modifier.fillMaxWidth(),
                        shape = textFieldShape,
                        keyboardOptions = KeyboardOptions(
                            keyboardType = KeyboardType.Text,
                            imeAction = ImeAction.Next
                        ),
                        keyboardActions = KeyboardActions(
                            onNext = { focusManager.moveFocus(FocusDirection.Down) }
                        ),
                        enabled = !isLoading,
                        maxLines = 2
                    )

                    HorizontalDivider(modifier = Modifier.padding(vertical = 20.dp), color = MaterialTheme.colorScheme.outlineVariant)

                    Text(
                        text = stringResource(R.string.repo_settings_section_auth),
                        style = MaterialTheme.typography.labelLarge,
                        color = MaterialTheme.colorScheme.primary,
                        modifier = Modifier.padding(bottom = 12.dp)
                    )

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        FilterChip(
                            selected = authMode == GitAuthMode.HTTPS,
                            onClick = { authMode = GitAuthMode.HTTPS },
                            label = { Text(stringResource(R.string.auth_mode_https)) },
                            leadingIcon = { Icon(Icons.Default.Lock, contentDescription = null) }
                        )
                        FilterChip(
                            selected = authMode == GitAuthMode.SSH,
                            onClick = { authMode = GitAuthMode.SSH },
                            label = { Text(stringResource(R.string.auth_mode_ssh)) },
                            leadingIcon = { Icon(Icons.Default.Key, contentDescription = null) }
                        )
                    }

                    Spacer(Modifier.height(12.dp))

                    if (authMode == GitAuthMode.HTTPS) {
                    OutlinedTextField(
                        value = token,
                        onValueChange = { token = it },
                        label = { Text(stringResource(R.string.clone_token_label)) },
                        leadingIcon = { Icon(Icons.Default.VpnKey, contentDescription = null) },
                        trailingIcon = {
                            val image = if (tokenVisible) Icons.Default.Visibility else Icons.Default.VisibilityOff
                            val description = if (tokenVisible) "Hide token" else "Show token"

                            IconButton(onClick = { tokenVisible = !tokenVisible }) {
                                Icon(imageVector = image, contentDescription = description)
                            }
                        },
                        modifier = Modifier.fillMaxWidth(),
                        shape = textFieldShape,
                        visualTransformation = if (tokenVisible) VisualTransformation.None else PasswordVisualTransformation(),
                        keyboardOptions = KeyboardOptions(
                            keyboardType = KeyboardType.Password,
                            imeAction = ImeAction.Done
                        ),
                        keyboardActions = KeyboardActions(
                            onDone = { focusManager.clearFocus() }
                        ),
                        enabled = !isLoading,
                        singleLine = true // Ensures password dots align perfectly
                    )

                    AnimatedVisibility(
                        visible = token.isEmpty() && lastUsedToken.isNotEmpty(),
                        enter = fadeIn() + expandVertically(),
                        exit = fadeOut() + shrinkVertically()
                    ) {
                        Row(
                            modifier = Modifier.padding(top = 8.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                text = "Use last token?",
                                style = MaterialTheme.typography.labelMedium,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                            Spacer(Modifier.width(8.dp))
                            SuggestionChip(
                                onClick = { token = lastUsedToken },
                                label = { Text("Restore", fontSize = 12.sp) },
                                shape = RoundedCornerShape(8.dp)
                            )
                        }
                    }

                    Spacer(Modifier.height(12.dp))

                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Switch(
                            checked = saveToken,
                            onCheckedChange = { isChecked ->
                                saveToken = isChecked
                            },
                            enabled = !isLoading
                        )
                        Spacer(Modifier.width(12.dp))
                        Text(
                            text = stringResource(R.string.clone_remember_token),
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                    } else {
                        Text(
                            text = stringResource(R.string.ssh_clone_help),
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        Spacer(Modifier.height(10.dp))
                        ExpandableSshTextField(
                            value = sshPrivateKey,
                            onValueChange = { sshPrivateKey = it },
                            label = { Text(stringResource(R.string.ssh_private_key_label)) },
                            leadingIcon = Icons.Default.Key,
                            enabled = !isLoading,
                            isSecret = true,
                            expandDescription = stringResource(R.string.ssh_expand_field),
                            collapseDescription = stringResource(R.string.ssh_collapse_field),
                            showDescription = stringResource(R.string.ssh_show_value),
                            hideDescription = stringResource(R.string.ssh_hide_value),
                            modifier = Modifier,
                            maxExpandedLines = 10
                        )
                        Spacer(Modifier.height(10.dp))
                        ExpandableSshTextField(
                            value = sshPassphrase,
                            onValueChange = { sshPassphrase = it },
                            label = { Text(stringResource(R.string.ssh_passphrase_label)) },
                            leadingIcon = Icons.Default.Password,
                            enabled = !isLoading,
                            isSecret = true,
                            expandDescription = stringResource(R.string.ssh_expand_field),
                            collapseDescription = stringResource(R.string.ssh_collapse_field),
                            showDescription = stringResource(R.string.ssh_show_value),
                            hideDescription = stringResource(R.string.ssh_hide_value),
                            modifier = Modifier,
                            maxExpandedLines = 3,
                            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password)
                        )
                        Spacer(Modifier.height(10.dp))
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            ExpandableSshTextField(
                                value = sshPublicKey,
                                onValueChange = { sshPublicKey = it },
                                label = { Text(stringResource(R.string.ssh_public_key_label)) },
                                leadingIcon = Icons.Default.Key,
                                enabled = !isLoading,
                                expandDescription = stringResource(R.string.ssh_expand_field),
                                collapseDescription = stringResource(R.string.ssh_collapse_field),
                                showDescription = stringResource(R.string.ssh_show_value),
                                hideDescription = stringResource(R.string.ssh_hide_value),
                                modifier = Modifier.weight(1f),
                                maxExpandedLines = 4
                            )
                            IconButton(
                                onClick = {
                                    val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as? ClipboardManager
                                    clipboard?.setPrimaryClip(
                                        ClipData.newPlainText("AndroidGit SSH public key", sshPublicKey)
                                    )
                                },
                                enabled = !isLoading && sshPublicKey.isNotBlank()
                            ) {
                                Icon(
                                    Icons.Default.ContentCopy,
                                    contentDescription = stringResource(R.string.repo_settings_ssh_copy_public)
                                )
                            }
                        }
                        Text(
                            text = stringResource(R.string.ssh_public_key_help),
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            modifier = Modifier.padding(top = 6.dp)
                        )
                        OutlinedButton(
                            onClick = {
                                val result = runCatching {
                                    authManager.generateKeyPair(
                                        passphrase = sshPassphrase,
                                        email = prefsManager.getUserEmail()
                                    )
                                }
                                result.onSuccess { generated ->
                                    sshPrivateKey = generated.privateKey
                                    sshPublicKey = generated.publicKey
                                    sshGenerationError = ""
                                    sshGenerationInfo = context.getString(R.string.ssh_generated_fmt, generated.algorithm)
                                }.onFailure { error ->
                                    sshGenerationInfo = ""
                                    sshGenerationError = buildString {
                                        append(error::class.java.simpleName)
                                        error.message?.takeIf { it.isNotBlank() }?.let {
                                            append(": ")
                                            append(it)
                                        }
                                    }
                                }
                            },
                            enabled = !isLoading,
                            modifier = Modifier.padding(top = 10.dp)
                        ) {
                            Icon(Icons.Default.AutoFixHigh, contentDescription = null)
                            Spacer(Modifier.width(8.dp))
                            Text(stringResource(R.string.ssh_generate_key))
                        }
                        if (sshGenerationInfo.isNotBlank()) {
                            Text(
                                text = sshGenerationInfo,
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.primary,
                                modifier = Modifier.padding(top = 8.dp)
                            )
                        }
                        if (sshGenerationError.isNotBlank()) {
                            Text(
                                text = sshGenerationError,
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.error,
                                modifier = Modifier.padding(top = 8.dp)
                            )
                        }
                    }
                }
            }

            Spacer(Modifier.height(32.dp))

            Button(
                onClick = {
                    focusManager.clearFocus()
                    if (parsedRemoteUrl == null) {
                        focusManager.clearFocus()
                    } else if (authMode == GitAuthMode.HTTPS) {
                        prefsManager.setAuthMode(GitAuthMode.HTTPS)
                        if (saveToken && token.isNotEmpty()) {
                            prefsManager.saveToken(token)
                        } else if (!saveToken) {
                            prefsManager.clearToken()
                        }
                        viewModel.cloneRepository(
                            repoUrl.trim(),
                            folderName,
                            GitAuthConfig(GitAuthMode.HTTPS, token = token),
                            onCloneSuccess
                        )
                    } else {
                        prefsManager.setAuthMode(GitAuthMode.SSH)
                        prefsManager.saveSshKey(sshPrivateKey, sshPublicKey, sshPassphrase)
                        viewModel.cloneRepository(
                            repoUrl.trim(),
                            folderName,
                            GitAuthConfig(GitAuthMode.SSH, privateKey = sshPrivateKey, passphrase = sshPassphrase),
                            onCloneSuccess
                        )
                    }
                },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(56.dp),
                shape = RoundedCornerShape(16.dp),
                enabled = !isLoading && parsedRemoteUrl != null &&
                    (authMode == GitAuthMode.HTTPS || sshPrivateKey.isNotBlank())
            ) {
                if (isLoading) {
                    CircularProgressIndicator(
                        modifier = Modifier.size(24.dp),
                        color = MaterialTheme.colorScheme.onPrimary,
                        strokeWidth = 2.5.dp
                    )
                } else {
                    Icon(Icons.Default.CloudDownload, contentDescription = null)
                    Spacer(Modifier.width(12.dp))
                    Text(
                        text = stringResource(R.string.clone_btn_action),
                        style = MaterialTheme.typography.titleMedium
                    )
                }
            }

            Spacer(Modifier.height(24.dp))

            AnimatedVisibility(
                visible = isLoading || statusMessage.isNotEmpty(),
                enter = fadeIn() + slideInVertically(initialOffsetY = { 40 }),
                exit = fadeOut() + slideOutVertically(targetOffsetY = { 40 })
            ) {
                val containerColor = when {
                    isLoading -> MaterialTheme.colorScheme.secondaryContainer.copy(alpha = 0.7f)
                    statusType == SnackbarType.ERROR -> MaterialTheme.colorScheme.errorContainer
                    statusType == SnackbarType.SUCCESS -> Color(0xFFE8F5E9)
                    else -> MaterialTheme.colorScheme.surfaceVariant
                }

                val contentColor = when {
                    isLoading -> MaterialTheme.colorScheme.onSecondaryContainer
                    statusType == SnackbarType.ERROR -> MaterialTheme.colorScheme.onErrorContainer
                    statusType == SnackbarType.SUCCESS -> Color(0xFF2E7D32)
                    else -> MaterialTheme.colorScheme.onSurfaceVariant
                }

                Surface(
                    color = containerColor,
                    shape = RoundedCornerShape(24.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(
                        modifier = Modifier.padding(20.dp),
                        horizontalAlignment = Alignment.CenterHorizontally
                    ) {
                        if (isLoading) {
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween
                            ) {
                                Text(
                                    text = cloneTaskName.ifEmpty { "Initializing..." },
                                    style = MaterialTheme.typography.titleMedium,
                                    fontWeight = FontWeight.Bold,
                                    color = contentColor
                                )
                                Text(
                                    text = "${(cloneProgress * 100).toInt()}%",
                                    style = MaterialTheme.typography.titleLarge,
                                    fontWeight = FontWeight.Black,
                                    color = contentColor
                                )
                            }
                            
                            Spacer(Modifier.height(12.dp))
                            
                            LinearProgressIndicator(
                                progress = { cloneProgress },
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(10.dp)
                                    .clip(RoundedCornerShape(5.dp)),
                                color = MaterialTheme.colorScheme.primary,
                                trackColor = contentColor.copy(alpha = 0.2f)
                            )
                            
                            if (cloneTaskDetails.isNotEmpty()) {
                                Text(
                                    text = cloneTaskDetails,
                                    style = MaterialTheme.typography.bodySmall,
                                    color = contentColor.copy(alpha = 0.8f),
                                    modifier = Modifier.padding(top = 8.dp).align(Alignment.Start)
                                )
                            }
                        } else {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Icon(
                                    imageVector = when(statusType) {
                                        SnackbarType.ERROR -> Icons.Default.Error
                                        SnackbarType.SUCCESS -> Icons.Default.CheckCircle
                                        else -> Icons.Default.Info
                                    },
                                    contentDescription = null,
                                    tint = contentColor
                                )
                                Spacer(Modifier.width(12.dp))
                                Text(
                                    text = statusMessage,
                                    color = contentColor,
                                    style = MaterialTheme.typography.bodyMedium,
                                    fontWeight = FontWeight.Medium,
                                    modifier = Modifier.weight(1f)
                                )
                                IconButton(onClick = { viewModel.clearStatus() }) {
                                    Icon(Icons.Default.Close, contentDescription = null, tint = contentColor.copy(alpha = 0.5f), modifier = Modifier.size(18.dp))
                                }
                            }
                        }
                    }
                }
            }

            Spacer(Modifier.height(40.dp))
        }
    }
}
