package com.android.git.ui.screens

import androidx.activity.compose.BackHandler
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.expandVertically
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.shrinkVertically
import androidx.compose.animation.slideInVertically
import androidx.compose.animation.slideOutVertically
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.FocusDirection
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalFocusManager
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.android.git.R
import com.android.git.data.PreferencesManager
import com.android.git.ui.components.SnackbarType
import com.android.git.ui.viewmodel.MainViewModel
import java.io.File

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CloneScreen(
    viewModel: MainViewModel,
    onBack: () -> Unit,
    onCloneSuccess: (File) -> Unit
) {
    val context = LocalContext.current
    val prefsManager = remember { PreferencesManager(context) }
    val focusManager = LocalFocusManager.current

    val activeToken = remember { prefsManager.getToken() }
    val lastUsedToken = remember { prefsManager.getLastValidToken() }

    var repoUrl by remember { mutableStateOf("") }
    var folderName by remember { mutableStateOf("") }
    var autoGeneratedName by remember { mutableStateOf("") }
    var token by remember { mutableStateOf(activeToken) }
    var saveToken by remember { mutableStateOf(activeToken.isNotEmpty()) }

    val isLoading = viewModel.isLoading
    val statusMessage = viewModel.statusMessage
    val statusType = viewModel.statusType

    val textFieldShape = RoundedCornerShape(16.dp)

    LaunchedEffect(repoUrl) {
        val cleanUrl = repoUrl.trim().removeSuffix("/")
        if (cleanUrl.contains("/")) {
            val name = cleanUrl.substringAfterLast("/").removeSuffix(".git")
            if (name.isNotBlank() && (folderName.isEmpty() || folderName == autoGeneratedName)) {
                folderName = name
                autoGeneratedName = name
            }
        }
    }

    BackHandler(enabled = !isLoading) {
        viewModel.clearStatus()
        onBack()
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.clone_title), fontWeight = FontWeight.SemiBold) },
                navigationIcon = {
                    IconButton(onClick = onBack, enabled = !isLoading) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = stringResource(R.string.action_back)
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surface,
                    titleContentColor = MaterialTheme.colorScheme.onSurface
                )
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(horizontal = 16.dp)
                .verticalScroll(rememberScrollState()),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Spacer(modifier = Modifier.height(16.dp))

            ElevatedCard(
                modifier = Modifier.fillMaxWidth(),
                shape = MaterialTheme.shapes.large,
                colors = CardDefaults.elevatedCardColors(
                    containerColor = MaterialTheme.colorScheme.surfaceContainerLow
                ),
                elevation = CardDefaults.elevatedCardElevation(defaultElevation = 2.dp)
            ) {
                Column(modifier = Modifier.padding(20.dp)) {

                    Text(
                        text = stringResource(R.string.repo_settings_section_remote),
                        style = MaterialTheme.typography.labelLarge,
                        color = MaterialTheme.colorScheme.primary,
                        modifier = Modifier.padding(bottom = 12.dp)
                    )

                    OutlinedTextField(
                        value = repoUrl,
                        onValueChange = { repoUrl = it },
                        label = { Text(stringResource(R.string.clone_url_label)) },
                        placeholder = { Text(stringResource(R.string.clone_url_placeholder)) },
                        leadingIcon = { Icon(Icons.Default.Link, contentDescription = null) },
                        modifier = Modifier.fillMaxWidth(),
                        shape = textFieldShape,
                        keyboardOptions = KeyboardOptions(
                            keyboardType = KeyboardType.Uri,
                            imeAction = ImeAction.Next
                        ),
                        keyboardActions = KeyboardActions(
                            onNext = { focusManager.moveFocus(FocusDirection.Down) }
                        ),
                        enabled = !isLoading,
                        maxLines = Int.MAX_VALUE
                    )

                    Spacer(Modifier.height(16.dp))

                    OutlinedTextField(
                        value = folderName,
                        onValueChange = { folderName = it },
                        label = { Text(stringResource(R.string.clone_folder_label)) },
                        placeholder = { Text(stringResource(R.string.clone_folder_hint)) },
                        leadingIcon = { Icon(Icons.Default.Folder, contentDescription = null) },
                        modifier = Modifier.fillMaxWidth(),
                        shape = textFieldShape,
                        keyboardOptions = KeyboardOptions(
                            keyboardType = KeyboardType.Text,
                            imeAction = ImeAction.Next
                        ),
                        keyboardActions = KeyboardActions(
                            onNext = { focusManager.moveFocus(FocusDirection.Down) }
                        ),
                        enabled = !isLoading,
                        maxLines = 2
                    )

                    HorizontalDivider(modifier = Modifier.padding(vertical = 20.dp), color = MaterialTheme.colorScheme.outlineVariant)

                    Text(
                        text = stringResource(R.string.repo_settings_section_auth),
                        style = MaterialTheme.typography.labelLarge,
                        color = MaterialTheme.colorScheme.primary,
                        modifier = Modifier.padding(bottom = 12.dp)
                    )

                    OutlinedTextField(
                        value = token,
                        onValueChange = { token = it },
                        label = { Text(stringResource(R.string.clone_token_label)) },
                        leadingIcon = { Icon(Icons.Default.VpnKey, contentDescription = null) },
                        modifier = Modifier.fillMaxWidth(),
                        shape = textFieldShape,
                        keyboardOptions = KeyboardOptions(
                            keyboardType = KeyboardType.Text,
                            imeAction = ImeAction.Done
                        ),
                        keyboardActions = KeyboardActions(
                            onDone = { focusManager.clearFocus() }
                        ),
                        enabled = !isLoading,
                        maxLines = Int.MAX_VALUE
                    )

                    AnimatedVisibility(
                        visible = token.isEmpty() && lastUsedToken.isNotEmpty(),
                        enter = fadeIn() + expandVertically(),
                        exit = fadeOut() + shrinkVertically()
                    ) {
                        Row(
                            modifier = Modifier.padding(top = 8.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                text = "Use last token?",
                                style = MaterialTheme.typography.labelMedium,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                            Spacer(Modifier.width(8.dp))
                            SuggestionChip(
                                onClick = { token = lastUsedToken },
                                label = { Text("Restore", fontSize = 12.sp) },
                                shape = RoundedCornerShape(8.dp)
                            )
                        }
                    }

                    Spacer(Modifier.height(12.dp))

                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Switch(
                            checked = saveToken,
                            onCheckedChange = { isChecked ->
                                saveToken = isChecked
                                if (!isChecked) prefsManager.clearToken()
                            },
                            enabled = !isLoading
                        )
                        Spacer(Modifier.width(12.dp))
                        Text(
                            text = stringResource(R.string.clone_remember_token),
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }
            }

            Spacer(Modifier.height(32.dp))

            Button(
                onClick = {
                    focusManager.clearFocus()
                    if (saveToken && token.isNotEmpty()) {
                        prefsManager.saveToken(token)
                    }
                    viewModel.cloneRepository(repoUrl, folderName, token, onCloneSuccess)
                },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(56.dp),
                shape = RoundedCornerShape(16.dp),
                enabled = !isLoading && repoUrl.isNotBlank()
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.Center
                ) {
                    if (isLoading) {
                        CircularProgressIndicator(
                            modifier = Modifier.size(24.dp),
                            color = MaterialTheme.colorScheme.onPrimary,
                            strokeWidth = 2.5.dp
                        )
                        Spacer(Modifier.width(16.dp))
                        Text(
                            text = stringResource(R.string.clone_status_running),
                            style = MaterialTheme.typography.titleMedium
                        )
                    } else {
                        Icon(Icons.Default.CloudDownload, contentDescription = null)
                        Spacer(Modifier.width(12.dp))
                        Text(
                            text = stringResource(R.string.clone_btn_action),
                            style = MaterialTheme.typography.titleMedium
                        )
                    }
                }
            }

            Spacer(Modifier.height(24.dp))

            val statusBgColor = when (statusType) {
                SnackbarType.ERROR -> MaterialTheme.colorScheme.errorContainer
                SnackbarType.SUCCESS -> Color(0xFFE8F5E9)
                SnackbarType.WARNING -> Color(0xFFFFF8E1)
                SnackbarType.INFO -> MaterialTheme.colorScheme.secondaryContainer
            }

            val statusContentColor = when (statusType) {
                SnackbarType.ERROR -> MaterialTheme.colorScheme.onErrorContainer
                SnackbarType.SUCCESS -> Color(0xFF2E7D32)
                SnackbarType.WARNING -> Color(0xFFF57F17)
                SnackbarType.INFO -> MaterialTheme.colorScheme.onSecondaryContainer
            }

            val statusIcon = when (statusType) {
                SnackbarType.ERROR -> Icons.Default.Error
                SnackbarType.SUCCESS -> Icons.Default.CheckCircle
                SnackbarType.WARNING -> Icons.Default.Warning
                SnackbarType.INFO -> Icons.Default.Info
            }

            AnimatedVisibility(
                visible = statusMessage.isNotEmpty(),
                enter = fadeIn() + slideInVertically(initialOffsetY = { 20 }),
                exit = fadeOut() + slideOutVertically()
            ) {
                Surface(
                    color = statusBgColor,
                    shape = RoundedCornerShape(16.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Row(
                        modifier = Modifier.padding(16.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            imageVector = statusIcon,
                            contentDescription = null,
                            tint = statusContentColor
                        )
                        Spacer(modifier = Modifier.width(12.dp))
                        Text(
                            text = statusMessage,
                            color = statusContentColor,
                            style = MaterialTheme.typography.bodyMedium,
                            fontWeight = FontWeight.Medium
                        )
                    }
                }
            }

            Spacer(Modifier.height(32.dp))
        }
    }
}